# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='f_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='m_name',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='regis_no',
            new_name='registration_no',
        ),
    ]
