# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import studentinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_auto_20170327_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='thumbnail',
            field=models.FileField(default=django.utils.timezone.now, upload_to=studentinfo.models.get_upload_file_name),
            preserve_default=False,
        ),
    ]
